# Generated by Django 3.1.6 on 2021-02-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_url', models.URLField()),
                ('consult_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
                ('store_url', models.URLField()),
                ('sales', models.IntegerField(default=0)),
            ],
        ),
    ]
